{
    'name': 'Music School',
    'version': '1.0',
    'description': 'Module for music school',
    'summary': 'Music School Management',
    'category': 'Education',
    'author': 'Edu',
    'installable': True,
    'depends': [
        'base'
    ],
    'data': [
        'data/ir_cron.xml',
        'data/music_school_data.xml',
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'views/music_school_student_view.xml',
        'views/music_school_teacher_view.xml',
        'views/music_school_instrument_view.xml',
        'views/music_school_course_view.xml',
        'views/music_school_classroom_view.xml',
        'views/music_school_lesson_view.xml',
        'views/music_school_lesson_attendance_view.xml',
        'views/music_school_exam_view.xml',
        'views/music_school_exam_result_view.xml',
        'views/music_school_menuitems.xml',
        'wizard/music_school_course_change_state.xml',
        'wizard/music_school_lesson_create_wizard_view.xml',
        'report/music_school_course_report.xml',
        'report/music_school_course_report_simple.xml',
        'report/music_school_lesson_report.xml',
        'report/music_school_exam_report.xml',
    ],
    'auto_install': False,
    'application': False,
}